### ISSUE TITLE
Organizations and Authorities

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#10]
The organizations metadata (see the Org tab) seems to be a bit of a mix between organization (authority) and source (database owned by the organization).  I've cleaned some of it up, but it needs to refined. The organizations then need to be indicated on the DataSeries sheet, column L.

**Comment by takavarasha** [comment]
I removed the following items from the Orgs worksheet because they are products rather than organisations. I replaced removed item with the organisation responsible for the products

-Armed Conflict Location & Event Dataset
-DESA United Nations Indicators for Monitoring the Millennium Development Goals
-UNDP Human Development Reports
-Unicef Statistics and Monitoring
-United Nations Multilingual Terminology Database
