### ISSUE TITLE
PVX040 (ACLED incidents of violence) seems to be missing from the SW data

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#20]
Has it always been like that?  Should we disable it?

**Comment by alexandru-m-g** [comment]
PVX040 was not in the scraperwiki data when we were testing the import a few weeks ago.
There was an email chain about this called "Missing Indicator Types".
Hope this helps

**Comment by rosnfeld** [comment]
Duplicate of https://github.com/OCHA-DAP/dap-scrapers/issues/30 ? (intentional?)

**Comment by JavierTeran** [comment]
@takavarasha Please clarify and close this issue. Thanks Godfrey.

**Comment by takavarasha** [comment]
I believe this issue was resolved some time ago. This indicator is part of a number of indicators that were being looked at by SW. The results of this work are being recorded in the google spreadsheet below. I checked today's SW csv.zip and I saw that PVX040 had 807 data points in the value.csv file. 

https://docs.google.com/spreadsheets/d/1uxl3IM9mbXKA3MmA2x4M9-YnjDDhjZmyl2eCf9nNN4Q/edit#gid=0

Closing this one for now
