### ISSUE TITLE
Tags for Indicator-specific collections on CKAN

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#3]
We can programmatically create the CKAN collections for each indicator type (from SW).  If you want, we can include specific tags for each indicator (for example, the indicator for "km of roads" could be tagged with "transportation").  Rather than doing these in CKAN (where they would be lost if we had to rebuild the database), we can do it from another data-team-managed list.  When you think you have time to start working on that, let's talk about the best way to capture that info.

**Comment by luiscape** [comment]
@takavarasha How are we doing on this task? I am eager to close it! :dart: 

Can I help you review the tags in any way? I am much "freer" this week to work on Data Team tasks.

**Comment by JavierTeran** [comment]
That's a good idea. I think he is almost done but a QA is appreciated.

**Comment by takavarasha** [comment]
All the indicators were tagged last week. I am enhancing the tags this week because while the tagging method that we discussed works very well for search, does not work very well for users who will make use of the filters on the side of the search screen. I am doing this enhancement concurrently with issue #40. So I am closing this one for now.
