### ISSUE TITLE
Standardize expression of value units (column C).  

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#7]
Let's apply the same standardization to Source Units (column Q).
Sometimes it has "%" , sometimes "% of something", sometimes "percent . . .", sometimes "percentage".  We probably want to standardize these and also standardize capitalization, abbreviation etc.  The string in this column is how the units will be presented to users.

**Comment by takavarasha** [comment]
I standardized the expression of units in column C. The units in column Q now read the same as in column C.

**Comment by cjhendrix** [comment]
@takavarasha @JavierTeran 

I'm reopening this just to make sure you've seen it.  

I think I may have muddled this one a bit.  DataSeries Column C is how we store the units in the normalized database.  This would be the default of how we present it to users, though of course a given interface could manipulate those values and present the units differently.  So, changes to C (and D for that matter) are something that needs to be discussed between the dev and data teams.  I've made those columns gray to indicate that. 

DataSeries Column Q are the units that we receive from the source (in this case, from SW).  It is critical that these be accurate, based on your research of the original data source, otherwise we won't transform them correctly.  

So, based on the above, I have made the changes listed below.  Please have a look to be sure I haven't misinterpreted something about the data: 

**_population undernourished, millions**:   
- changed indicatorID to _PVN011_
- changed IndicatorName from _Population undernourished (millions)_ to _Population undernourished_
- changed valueUnits from _People (x1,000,000)_ to _People_

**CH100**:
- changed valueUnits from _US$ (x 1,000)_ to _US$_
- changed sourceUnits from _,000$ USD_ to _thousands_

**PSP010**:
- changed valueUnits from _People (x 1,000)_ to _People_

**PVH050**:
- changed valueUnits from _Deaths (x 1,000)_ to _Deaths_
