### ISSUE TITLE
Delete "attribute" indicators on ckan

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#87]
Please consider deleting any of the attribute indicators (currency code, short name, etc) since these do not meet our definition of an indicator (non numeric) and are therfore not graphable.  

![image](https://cloud.githubusercontent.com/assets/1654485/4663691/d5793e04-553d-11e4-83fe-19be744e5aa6.png)

Tagging @JavierTeran

**Comment by luiscape** [comment]
A couple of things here: 
1. They should be deleted as datasets from CKAN?
2. They should be deleted from CPS? Or, at least, put in a different table? This will prevent them to be served through the same API that serves indicator values.
3. They should be deleted from the API query list?

Let us know what you think.

**Comment by takavarasha** [comment]
I know that the attribute indicators which were left on CKAN when the wikipedia datasets were removed sometime before the launch. I believe this was because we use the attributes in the country centric reports. Will wait for @JavierTeran for decision on what to do with these on CKAN. The list of attribute indicators that I know to be on CKAN is as follows:

[CG020 Formal Name](https://data.hdx.rwlabs.org/dataset/formal_name)
[CG030 Short Name](https://data.hdx.rwlabs.org/dataset/short_name)
[CG070 Iso Country Alpha-3-Code](https://data.hdx.rwlabs.org/dataset/iso_country_alpha-3-code)
[CG080 Capital City](https://data.hdx.rwlabs.org/dataset/capital_city)
[CG100 Languages](https://data.hdx.rwlabs.org/dataset/languages)
[CG120 Currency Abbr](https://data.hdx.rwlabs.org/dataset/currency_abbr)
[CG140 Iso Currency Code](https://data.hdx.rwlabs.org/dataset/iso_currency_code)
[CG150 Income Category](https://data.hdx.rwlabs.org/dataset/income_category)
[CG290 Date Of Entry Into Un](https://data.hdx.rwlabs.org/dataset/date_of_entry_into_un)
[CG320 Country Code Iso Country Alpha-2-Code](https://data.hdx.rwlabs.org/dataset/country_code_iso_country_alpha-2-code)

**Comment by cjhendrix** [comment]
We need to leave them on CPS for now as they are used in the reports.  Creating a new attribute entity for them is low priority at the moment.  I think anyone sophisticated enough to use our API won't be too flummoxed by seeing an indicator for country name, etc.

But I think we _do_ need to delete the datasets on ckan, since they can't be graphed.

**Comment by luiscape** [comment]
Sounds good. Thanks @cjhendrix. Should we go ahead and delete those from CKAN @takavarasha and @JavierTeran ?

**Comment by JavierTeran** [comment]
Hi @cjhendrix @takavarasha @luiscape I totally agree. I just double checked and can't find them any more in the collections (xls, csv, readme). That was my only worry. We can delete the list as indicated above as soon as possible.

**Comment by takavarasha** [comment]
Deleted the list.
